### ISSUE TITLE
Java JDK issue on MacOS

### ISSUE THREAD

**Issue by MaxHedrm** [Umoxfo/brackets-w3cvalidation#11]
MacOS Version: Yosemite (10.10), El Capitan (10.11), Sierra (10.12), High Sierra (10.13), Mojave (10.14)
Brackets Version: 1.13 and prior
Plugin Version: 1.10
Java Version: 10.0.2, maybe 8u181 (anything other than Apple's Java 6 I'm guessing)

To use the “java” command-line tool you need to install a JDK.

<img width="532" alt="screenshot 2018-09-30 13 40 29" src="https://user-images.githubusercontent.com/6634839/46261299-4f1a8f00-c4b7-11e8-91f0-cc3ad43cc070.png">

This error usually means that you are tied to the Apple version or Java which has been deprecated since Yosemite (something like 4 years ago).

**Comment by Umoxfo** [comment]
This extension requires Java 8 or later and a JDK from Oracle must be installed instead of the JRE according to Oracle [System Requirements for Installing the JDK and JRE on macOS](https://docs.oracle.com/javase/10/install/installation-jdk-and-jre-macos.htm#JSJIG-GUID-E8A251B6-D9A9-4276-ABC8-CC0DAD62EA33).
